version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: spring-modular-postgress
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spring-modular